services:
  dev-db:
    image: postgres:18rc1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge
